CREATE PROCEDURE AYLARA_GORE_REZARVASYIN
(@BASAY int ,
 @ENDAY int )
 AS
 DECLARE
    CRS_DATE CURSOR FOR
    SELECT  COUNT(DATEPART(MONTH,BOOKING_DATE))
    FROM BOOKINGS
    WHERE DATEPART(MONTH,BOOKING_DATE) BETWEEN @BASAY AND @ENDAY

DECLARE @BOOKING_DATE INT
	BEGIN
    OPEN CRS_DATE
 
    FETCH NEXT FROM CRS_DATE INTO  @BOOKING_DATE
    WHILE @@FETCH_STATUS = 0
    BEGIN
            PRINT @BOOKING_DATE 
            FETCH NEXT FROM CRS_DATE INTO @BOOKING_DATE
    END
 
    CLOSE CRS_DATE
    DEALLOCATE CRS_DATE
 END
 
EXEC AYLAR_ARASINDA_REZARVASYON 2,5 