CREATE PROC SP_TRANSACTION_INSERTED
(
@ID INT,
@USER_ID INT,
@TRANSFER_ON DATETIME,
@AMOUNT FLOAT,
@STATUS TINYINT
)
AS
BEGIN
	IF EXISTS (SELECT * FROM TRANSACTIONS WHERE ID =@ID)
	BEGIN
		PRINT 'BU TRANSACTION MEVCUTTUR.BAÞKA BÝR TRANSACTION DENEYIN'
	END
	ELSE
	BEGIN
		INSERT INTO TRANSACTIONS(ID,USERID,TRANSFER_ON,AMOUNT,STATUS) VALUES (@ID,@USER_ID,@TRANSFER_ON,@AMOUNT,@STATUS)
		PRINT 'BAÞARILIYLA OLUÞTURDUNUZ.'
	END

END

EXEC SP_TRANSACTION_INSERTED 900108,123502,'2017-02-21 18:10:00.000',500,1


