CREATE PROC SP_TARIHLERE_GORE_ARA
@STAR_DATE DATE,
@END_DATE DATE
AS 
BEGIN

	DECLARE  @KONUM1 NVARCHAR(200)
	DECLARE  @KONUM2 NVARCHAR(200)
	DECLARE  @KONUM3 NVARCHAR(200)

	SELECT  @KONUM1 = C.NAME,@KONUM2 = CT.NAME,@KONUM3= S.NAME FROM PROPERTIES P
	INNER JOIN COUNTRIES C ON P.COUNTRY_ID = C.ID
	INNER JOIN CITIES CT ON P.CITY_ID = CT.ID
	INNER JOIN STATES S ON P.STATE_ID = S.ID
	WHERE @STAR_DATE =P.START_DATE 
	AND @END_DATE =P.END_DATE

		IF @KONUM1 IS NULL
		BEGIN
			RAISERROR ('Bu tarihler arasýnda böyle bir tatil yeri yok',16,1)
			RETURN
		END
		ELSE
		BEGIN 
			SELECT @KONUM1
		END

SELECT @KONUM1,@KONUM2,@KONUM3
	
END



