CREATE TABLE CMS_PAGE_LANGUAGES
(
ID INT PRIMARY KEY,
CMS_PAGE_ID INT,
LANGUAGE_ID INT,
DESCRIPTION VARCHAR(MAX),
	CONSTRAINT FK_CMS_PAGE FOREIGN KEY(CMS_PAGE_ID) REFERENCES CMS_PAGES(ID),
	CONSTRAINT FK_LANGUAGE_3 FOREIGN KEY(LANGUAGE_ID) REFERENCES LANGUAGE(ID)
)