CREATE TABLE DISPUTES
(
ID INT PRIMARY KEY,
USERID INT,
PROPERTY_ID INT,
BOOKING_ID INT,
NAME VARCHAR(200),
DESCRIPTION VARCHAR(MAX),
CREATED DATETIME,
MODIFIED DATETIME,
STATUS TINYINT,
	CONSTRAINT FK_PROPERTY_5 FOREIGN KEY(PROPERTY_ID) REFERENCES PROPERTIES(ID),
	CONSTRAINT FK_USER_5 FOREIGN KEY(USERID) REFERENCES USERS(ID),
	CONSTRAINT FK_BOOKING_2 FOREIGN KEY(BOOKING_ID) REFERENCES BOOKINGS(ID)
)