
CREATE TABLE PROPERTIES
(
ID INT PRIMARY KEY,
NAME VARCHAR(200),
DESCRIPTION VARCHAR(MAX),
USERID INT,
PROPERTY_TYPE_ID INT,
ROOM_TYPE_ID INT,
CATEGORY_ID INT,
SUBCATEGORY_ID INT,
COUNTRY_ID INT,
STATE_ID INT,
CITY_ID INT,
CURRENCY_ID INT,
ROOM_DETAIL_ID INT,
ADDRESS_ID INT,
START_DATE DATE,
END_DATE DATE,
PRICE FLOAT,
PRICE_TYPE_ID TINYINT,
MINUMUM_STAY INT,
CREATED DATETIME,
MODIFIED DATETIME,
STATUS TINYINT

	CONSTRAINT FK_USER FOREIGN KEY(USERID) REFERENCES USERS(ID),
	CONSTRAINT FK_PROPERTY_TYPE FOREIGN KEY(PROPERTY_TYPE_ID) REFERENCES PROPERTY_TYPE(ID),
	CONSTRAINT FK_ROOM_TYPE FOREIGN KEY(ROOM_TYPE_ID) REFERENCES ROOM_TYPE(ID),
	CONSTRAINT FK_CATEGORY_2 FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORIES(ID),
	CONSTRAINT FK_SUBCATEGORIES FOREIGN KEY(SUBCATEGORY_ID) REFERENCES SUBCATEGORIES(ID),
	CONSTRAINT FK_COUNTRY_3 FOREIGN KEY(COUNTRY_ID) REFERENCES COUNTRIES(ID),
	CONSTRAINT FK_STATE_2 FOREIGN KEY(STATE_ID) REFERENCES STATES(ID),
	CONSTRAINT FK_CITY FOREIGN KEY(CITY_ID) REFERENCES CITIES(ID),
	CONSTRAINT FK_CURRENCY FOREIGN KEY(CURRENCY_ID) REFERENCES CURRENCIES(ID),
	CONSTRAINT FK_ROOM_DETAILS FOREIGN KEY(ROOM_DETAIL_ID) REFERENCES ROOM_DETAIL(ID),
	CONSTRAINT FK_ADDRESS FOREIGN KEY(ADDRESS_ID) REFERENCES ADDRESS(ID),
	CONSTRAINT FK_PRICE_TYPE FOREIGN KEY(PRICE_TYPE_ID) REFERENCES PRICE_TYPE(ID)
)