CREATE TABLE PROPERTY_REVIEWS
(
ID INT PRIMARY KEY,
PROPERTY_ID INT,
REVIEW_BY_USER INT,
BOOKING_ID INT,
COMMENT VARCHAR(MAX),
RATING TINYINT,
CREATED DATETIME,
MODIFIED DATETIME,
STATUS TINYINT,
	CONSTRAINT FK_PROPERTY_4 FOREIGN KEY(PROPERTY_ID) REFERENCES PROPERTIES(ID),
	CONSTRAINT FK_BOOKING FOREIGN KEY(BOOKING_ID) REFERENCES BOOKINGS(ID)
)