CREATE TABLE PROPERTY_AMENITIES(
ID INT PRIMARY KEY,
PROPERTY_ID INT,
AMENITY_ID INT,
CREATED DATETIME,
MODIFIED DATETIME,
STATUS TINYINT,
	CONSTRAINT FK_PROPERTY_6 FOREIGN KEY(PROPERTY_ID) REFERENCES PROPERTIES(ID),
	CONSTRAINT FK_AMENTIES FOREIGN KEY(AMENITY_ID) REFERENCES AMENTIES(ID)
)
