CREATE TABLE SUBCATEGORIES
(
ID INT PRIMARY KEY,
CATEGORY_ID INT,
NAME VARCHAR(500),
DESCRIPTION VARCHAR(MAX),
CREATED DATETIME,
MODIFIED DATETIME,
STATUS TINYINT,
	CONSTRAINT FK_CATEGORY FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORIES(ID)
)
