CREATE TABLE TRANSACTIONS
(
ID INT PRIMARY KEY,
PROPERTY_ID INT,
USERID INT,
SITE_FEES FLOAT,
AMOUNT FLOAT,
TRANSFER_ON DATETIME,
CURRENCY_ID INT,
PROMO_CODE_ID INT,
DISCOUNT_AMOUNT FLOAT,
CREATED DATETIME,
MODIFIED DATETIME,
STATUS TINYINT
	CONSTRAINT FK_PROPERTY_2 FOREIGN KEY(PROPERTY_ID) REFERENCES PROPERTIES(ID),
	CONSTRAINT FK_USER_2 FOREIGN KEY(USERID) REFERENCES USERS(ID),
	CONSTRAINT FK_CURRENCY_2 FOREIGN KEY(CURRENCY_ID) REFERENCES CURRENCIES(ID),
	CONSTRAINT FK_PROMO_CODE FOREIGN KEY(PROMO_CODE_ID) REFERENCES PROMO_CODES(ID)
)