
CREATE TABLE USERS
(
ID INT PRIMARY KEY,
FIRST_NAME VARCHAR(200),
LAST_NAME VARCHAR(200),
EMAIL VARCHAR(200),
PASSWORD VARCHAR(10),
USER_TYPE_ID TINYINT,
BIRTHDAY DATE,
GENDER CHAR(5),
LOGIN_WITH_ID TINYINT,
PHONE CHAR(12),
RECEIVE_COUPON INT,
COUNTRY_ID INT,
CREATED DATETIME,
MODIFIED DATETIME,
STATUS TINYINT,
LANGUAGE_ID INT
	CONSTRAINT FK_USER_TYPE FOREIGN KEY(USER_TYPE_ID) REFERENCES USER_TYPE(ID),
	CONSTRAINT FK_LOGIN_WITH FOREIGN KEY(LOGIN_WITH_ID) REFERENCES LOGIN_WITH(ID),
	CONSTRAINT FK_COUNTRY_2 FOREIGN KEY(COUNTRY_ID) REFERENCES COUNTRIES(ID),
	CONSTRAINT FK_LANGUAGE_2 FOREIGN KEY(LANGUAGE_ID) REFERENCES LANGUAGE(ID)
)