
CREATE VIEW VW_PET_PROPERTY
AS
SELECT C.NAME AS COUNTRY,PR.NAME AS PROPERTY,A.NAME AS AMENITY FROM AMENTIES A
JOIN PROPERTY_AMENITIES P ON A.ID=P.AMENITY_ID
JOIN PROPERTIES PR ON PR.ID=P.PROPERTY_ID
JOIN COUNTRIES C ON C.ID=PR.COUNTRY_ID
WHERE A.NAME LIKE '%PET%'
AND A.STATUS=1





