CREATE VIEW VW_OZELLIK_DETAYLI
AS
SELECT C.NAME_,S.NAMES,P.NAME,PT.NAMES_,B.BOOKING_DATE,COUNT(B.ID) AS REZERVASYON_TARIHI_SAYISI ,AVG(B.PRICE_FOR_STAY) AS ORTALAMA_KALMA_UCRETI ,SUM(B.SITE_FEES) AS TOPLAM_YER_UCRETI
FROM PROPERTIES P 
LEFT JOIN BOOKINGS B ON P.ID = B.PROPERTY_ID
INNER JOIN PROPERTY_TYPE PT ON P.PROPERTY_TYPE_ID = PT.ID
INNER JOIN ROOM_TYPE R ON P.ROOM_TYPE_ID = R.ID
INNER JOIN CATEGORIES C ON P.CATEGORY_ID = C.ID
INNER JOIN SUBCATEGORIES S ON P.SUBCATEGORY_ID = S.ID
INNER JOIN USERS U ON B.USERID = U.ID
GROUP BY C.NAME_,S.NAMES,P.NAME,PT.NAMES_,B.BOOKING_DATE


