CREATE VIEW VW_AYLARA_GÖRE_REZARVASYONLAR
AS
SELECT DATEPART(YEAR,B.BOOKING_DATE) YIL,
CASE 
    WHEN DATEPART(MONTH,B.BOOKING_DATE)=1 THEN 'OCAK'
	WHEN DATEPART(MONTH,B.BOOKING_DATE)=2 THEN 'ŞUBAT'
	WHEN DATEPART(MONTH,B.BOOKING_DATE)=3 THEN 'MART'
	WHEN DATEPART(MONTH,B.BOOKING_DATE)=4 THEN 'NİSAN'
	WHEN DATEPART(MONTH,B.BOOKING_DATE)=5 THEN 'MAYIS'
	WHEN DATEPART(MONTH,B.BOOKING_DATE)=6 THEN 'OHAZİRAN'
	WHEN DATEPART(MONTH,B.BOOKING_DATE)=7 THEN 'TEMMUZ'
	WHEN DATEPART(MONTH,B.BOOKING_DATE)=8 THEN 'AĞUSTOS'
	WHEN DATEPART(MONTH,B.BOOKING_DATE)=9 THEN 'EYLÜL'
	WHEN DATEPART(MONTH,B.BOOKING_DATE)=10 THEN 'EKİM'
	WHEN DATEPART(MONTH,B.BOOKING_DATE)=11 THEN 'KASIM'
	WHEN DATEPART(MONTH,B.BOOKING_DATE)=12 THEN 'ARALIK'
	
END AS AY,
SUM(T.AMOUNT) TOPLAMMIKTAR,
AVG(T.SITE_FEES) ORTALAMAGIRISUCRETI,COUNT(B.ID) REZARVASYONSAYISI,COUNT(DISTINCT U.ID) AS MUSTERISAYISI
FROM BOOKINGS B 
INNER JOIN TRANSACTIONS T ON B.TRANSACTION_ID = T.ID
INNER JOIN USERS U ON B.USERID = U.ID
GROUP BY DATEPART(YEAR,B.BOOKING_DATE),DATEPART(MONTH,B.BOOKING_DATE)
