USE [Airbnb_Booking]
GO

/****** Object:  View [dbo].[BOOKING_COUNT]    Script Date: 15.01.2021 17:49:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[BOOKING_COUNT]
AS
SELECT ID,COUNT(ID) AS "BOOKING_COUNT"
FROM BOOKING_AND_CUSTOMERS_LIST
GROUP BY ID
GO


