USE [Airbnb_Booking]
GO

/****** Object:  View [dbo].[AMOUNT_PAID_500PLUS]    Script Date: 15.01.2021 17:48:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[AMOUNT_PAID_500PLUS]
AS
SELECT P.NAME AS PROPERTY_NAME,U.ID AS USER_ID,U.FIRST_NAME,U.LAST_NAME,U.GENDER,B.ID AS BOOKING_ID,C.NAME AS COUNTRY_NAME
FROM USERS U
INNER JOIN BOOKINGS B ON U.ID=B.USERID 
INNER JOIN PROPERTIES P ON B.PROPERTY_ID=P.ID
INNER JOIN COUNTRIES C ON P.COUNTRY_ID=C.ID
WHERE B.AMOUNT_PAID>500 AND B.IS_REFUND=1
GO


