USE [Airbnb_Booking]
GO

/****** Object:  View [dbo].[BOOKING_AND_CUSTOMERS_LIST]    Script Date: 15.01.2021 17:48:42 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[BOOKING_AND_CUSTOMERS_LIST]
AS
SELECT U.ID, U.FIRST_NAME,U.LAST_NAME,B.CHECK_IN_DATE,B.CHECK_OUT_DATE,B.AMOUNT_PAID
FROM USERS U
INNER JOIN BOOKINGS B ON U.ID=B.USERID
GO


