Create Function Fn_PT_REVIEW(@propertyType Nvarchar(15))
Returns Table
As
Return(SELECT PT.NAME,PR.COMMENT,PR.RATING,CASE
			WHEN PR.RATING>7  THEN '*****'
			WHEN PR.RATING>5  THEN '***'
			WHEN PR.RATING>=3  THEN '**'
			WHEN PR.RATING>=1 THEN '*'
			ELSE 'Yýldýz Yok' 
		END AS 'RATING OUTPUT'  FROM
PROPERTY_REVIEWS PR left JOIN PROPERTIES P ON P.ID=PR.PROPERTY_ID
INNER JOIN PROPERTY_TYPE PT  ON  PT.ID=P.PROPERTY_TYPE_ID where @propertyType=PT.NAME )

SELECT * FROM Fn_PT_REVIEW('"Condominium')---ÖRNEK