
CREATE FUNCTION REVARVAZYON_BILGILERI(@AY AS INT)
RETURNS TABLE 
AS 
RETURN
(
SELECT MIN(PRICE_FOR_STAY) AS MINPRICE,
	   MAX(PRICE_FOR_STAY) AS MAXPRICE,
	   AVG(PRICE_FOR_STAY) AS AVGPRICE,
	   COUNT(ID) AS TOTALBOOKING

FROM BOOKINGS
WHERE DATEPART(MONTH,BOOKING_DATE)=@AY
)

SELECT * FROM DBO.REVARVAZYON_BILGILERI(2)
